spring:
  application:
    name: admin-server
  boot:
    admin:
      discovery:
        ignored-services: admin-server
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

server:
  port: 9090